most_relevant_columns = ['champion', 'kills', 'deaths', 'assists', 'doublekills', 'firstbloodkill', 'firstbloodassist', 'firstbloodvictim','damagetochampions', 'dpm', 'damageshare', 'damagetakenperminute', 'damagemitigatedperminute', 'damagetotowers', 'wardsplaced', 'visionscore', 'totalgold', 'minionkills', 'monsterkills', 'xpat10', 'csat10', 'goldat10', 'xpat15', 'csat15', 'goldat15', 'xpat20', 'csat20', 'goldat20', 'xpat25', 'csat25', 'goldat25']
most_relevant_columns += ['gamelength']

pos_order = ['top', 'jng', 'mid', 'bot', 'sup']

league_to_region_dict = {
    "LFL2":"EU", 
    "LPL": "CN", 
    "LCKC": "KR", 
    "LVP SL": "EU", 
    "LCK" : "KR", 
    "NLC": "EU", 
    "LCP": "APAC",
    "LEC": "EU",
    "HLL": "EU",
    "PRM": "EU", 
    "LFL": "EU",
    "LIT": "EU",
    "TCL": "EU",
    "HW": "EU",
    "LJL": "JP",
    "LTA S": "LAT",
    "LTA N": "NA",
    "RL": "EU",
    "NEXO": "EU", 
    "CD": "LAT",
    "EBL": "EU",
    "PCS": "APAC", 
    "ROL": "EU",
    "LPLOL": "EU", 
    "AL": "EU",
    "LTA": "NA",
    "VCS": "APAC",
    "FST": "INT",
    "EM": "EU",
    "LRS": "LAT",
    "LRN": "LAT",
    "NACL": "NA", 
    "LAS": "KR",
    "HC": "EU", 
    "PRMP": "EU",
    "HM": "EU", 
    "CT": "EU",
    "Asia Master": "INT",
    "MSI": "INT",
    "EWC": "INT",
    "WLDs": "INT",
    "ASI": "INT",
    "IC": "EU",
    "KeSPA": "KR",
    "DCup": "CN"
}